0:
  components: {}
  name: MainWindow
  type: MainWindow
1:
  components: {}
  name: Workspace
  type: Workspace
2:
  components: {}
  name: Editor
  positionInSceneCoords:
  - 5438.820062843673
  - 6526.584075412408
  type: Editor
  zoom: 0.6306514943255234
3:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  components: {}
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1600
  type: Global Lattice
5:
  components: {}
  name: Inspector
  size:
  - 500
  - -1
  type: Inspector
6:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linksIn: {}
  linksOut: {}
  name: Kernel Menu
  size:
  - 250
  - 250
  type: KernelMenu
7:
  automatic: true
  components:
    dimensions:
      name: Dimensions
      type: KernelComponent
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  fontsize: 12
  hyperparameters:
    lengthscale:
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 5.0
    scale:
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linkedPVs:
    19:
    - 0
    - 100
    27:
    - 0
    - 100
    28:
    - 0
    - 100
    29:
    - 0
    - 100
    30:
    - 0
    - 100
    31:
    - 0
    - 100
    32:
    - 0
    - 100
  linksIn: {}
  linksOut:
    12: kernel
    16: in
    37: in
  name: RBF Kernel HSTRs
  position:
  - 4562
  - 6708
  size:
  - 300
  - 374
  type: RBF Kernel
8:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linksIn: {}
  linksOut: {}
  name: Kernel Menu
  size:
  - 250
  - 250
  type: KernelMenu
9:
  automatic: true
  components:
    dimensions:
      name: Dimensions
      type: KernelComponent
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  fontsize: 12
  hyperparameters:
    lengthscale:
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 1.0
    period:
      description: periodicity affects frequency of oscillations
      type: vec
      value:
      - 4.0
    scale:
      description: magnitude of the kernel around the point
      type: float
      value: 1.0
  linkedPVs: {}
  linksIn: {}
  linksOut:
    16: in
    37: in
  name: Periodic Kernel
  position:
  - 4645
  - 7293
  size:
  - 300
  - 415
  type: Periodic Kernel
10:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 1.0
      valueType: float
  dtype: Y
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 116
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 116)'
  position:
  - 4577
  - 5501
  size:
  - 350
  - 115
  type: PV
11:
  automatic: true
  components:
    dimensions:
      name: Dimensions
      type: KernelComponent
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  fontsize: 12
  hyperparameters:
    lengthscale (RBF Kernel HSTRs):
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 5.0
    scale (RBF Kernel HSTRs):
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linkedPVs: {}
  linksIn: {}
  linksOut: {}
  name: Kernel
  size:
  - 300
  - 275
  type: Kernel
12:
  acqFunction: EI
  acqHyperparameter: 2
  components:
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      units: ''
      value: 0
      valueType: float
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linksIn:
    7: kernel
    10: decision
    19: decision
    20: decision
    21: decision
    22: decision
    23: decision
    25: decision
    26: decision
    27: decision
    28: decision
    29: decision
    30: decision
    31: decision
    32: decision
    34: objective
  linksOut: {}
  mode: maximise
  name: Single Task GP
  numParticles: 10000
  numSamples: 5
  numSteps: 20
  position:
  - 5291
  - 6140
  simPrecision: fp32
  size:
  - 600
  - 565
  type: Single Task GP
13:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: SURVIVAL_RATE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 120
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 120)'
  position:
  - 4008
  - 6301
  size:
  - 350
  - 115
  type: PV
14:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: SURVIVAL_RATE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 310
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 310)'
  position:
  - 4397
  - 6422
  size:
  - 350
  - 115
  type: PV
15:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: SURVIVAL_RATE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 280
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 280)'
  position:
  - 4399
  - 6301
  size:
  - 350
  - 115
  type: PV
16:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  hyperparameters:
    lengthscale (RBF Kernel HSTRs):
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 5.0
    scale (RBF Kernel HSTRs):
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linksIn:
    7: in
    9: in
  linksOut: {}
  name: Add
  position:
  - 5031
  - 7216
  size:
  - 350
  - 295
  type: Add
17:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: SURVIVAL_RATE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 254
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 254)'
  position:
  - 4004
  - 6669
  size:
  - 350
  - 115
  type: PV
18:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: SURVIVAL_RATE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 222
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 222)'
  position:
  - 4004
  - 6547
  size:
  - 350
  - 115
  type: PV
19:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: X
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 84
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 84)'
  position:
  - 4132
  - 5378
  size:
  - 350
  - 115
  type: PV
20:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 1.7094000000000003
      valueType: float
  dtype: Y
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 136
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 136)'
  position:
  - 4576
  - 5624
  size:
  - 350
  - 115
  type: PV
21:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
      valueType: float
  dtype: Y
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 270
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 270)'
  position:
  - 4571
  - 5988
  size:
  - 350
  - 115
  type: PV
22:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 3.25
      valueType: float
  dtype: Y
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 238
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 238)'
  position:
  - 4570
  - 5867
  size:
  - 350
  - 115
  type: PV
23:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: Y
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 296
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 296)'
  position:
  - 4569
  - 6110
  size:
  - 350
  - 115
  type: PV
24:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: SURVIVAL_RATE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 152
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 152)'
  position:
  - 4006
  - 6425
  size:
  - 350
  - 115
  type: PV
25:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 1.0
      valueType: float
  dtype: Y
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 88
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 88)'
  position:
  - 4578
  - 5381
  size:
  - 350
  - 115
  type: PV
26:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 10.0
      min: -10.0
      name: Kick
      type: SliderComponent
      units: ''
      value: -1.2820600000000013
      valueType: float
  dtype: Y
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 168
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 168)'
  position:
  - 4574
  - 5746
  size:
  - 350
  - 115
  type: PV
27:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: X
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 112
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 112)'
  position:
  - 4132
  - 5503
  size:
  - 350
  - 115
  type: PV
28:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: X
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 234
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 234)'
  position:
  - 4126
  - 5864
  size:
  - 350
  - 115
  type: PV
29:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: X
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 164
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 164)'
  position:
  - 4128
  - 5742
  size:
  - 350
  - 115
  type: PV
30:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: X
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 132
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 132)'
  position:
  - 4129
  - 5623
  size:
  - 350
  - 115
  type: PV
31:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: X
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 292
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 292)'
  position:
  - 4126
  - 6104
  size:
  - 350
  - 115
  type: PV
32:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: ''
      value: 0.0
  dtype: X
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linkedElement: 266
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 266)'
  position:
  - 4124
  - 5984
  size:
  - 350
  - 115
  type: PV
33:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linksIn: {}
  linksOut: {}
  name: Kernel Menu
  size:
  - 250
  - 250
  type: KernelMenu
34:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linksIn:
    13: in
    14: in
    15: in
    17: in
    18: in
    24: in
  linksOut:
    12: objective
  name: Add
  position:
  - 4913
  - 6397
  size:
  - 250
  - 100
  type: Add
35:
  automatic: true
  components:
    dimensions:
      name: Dimensions
      type: KernelComponent
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  fontsize: 12
  hyperparameters:
    lengthscale (RBF Kernel HSTRs):
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 5.0
    scale (RBF Kernel HSTRs):
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linkedPVs: {}
  linksIn: {}
  linksOut: {}
  name: Kernel
  size:
  - 300
  - 275
  type: Kernel
36:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  linksIn: {}
  linksOut: {}
  name: Kernel Menu
  size:
  - 250
  - 250
  type: KernelMenu
37:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  - SURVIVAL_RATE
  hyperparameters:
    lengthscale (RBF Kernel HSTRs):
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 5.0
    scale (RBF Kernel HSTRs):
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linksIn:
    7: in
    9: in
  linksOut: {}
  name: Multiply
  position:
  - 5029
  - 6836
  size:
  - 350
  - 295
  type: Multiply
