0:
  components: {}
  name: MainWindow
  type: MainWindow
1:
  components: {}
  name: Workspace
  type: Workspace
2:
  components: {}
  name: Editor
  positionInSceneCoords:
  - 5764.288815724709
  - 6376.299727023876
  type: Editor
  zoom: 0.7026018524526026
3:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  components: {}
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1600
  type: Global Lattice
5:
  components: {}
  name: Inspector
  size:
  - 500
  - -1
  type: Inspector
6:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linksIn: {}
  linksOut: {}
  name: Kernel Menu
  size:
  - 250
  - 250
  type: KernelMenu
7:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linksIn: {}
  linksOut: {}
  name: Kernel Menu
  size:
  - 250
  - 250
  type: KernelMenu
8:
  automatic: true
  components:
    dimensions:
      name: Dimensions
      type: KernelComponent
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  fontsize: 12
  hyperparameters:
    lengthscale (RBF Kernel (LTB HSTRs)):
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 1.0
    scale (RBF Kernel (LTB HSTRs)):
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linkedPVs: {}
  linksIn: {}
  linksOut: {}
  name: Kernel
  size:
  - 300
  - 275
  type: Kernel
9:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linksIn: {}
  linksOut: {}
  name: Kernel Menu
  size:
  - 250
  - 250
  type: KernelMenu
10:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 24
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 24)'
  position:
  - 4577
  - 5501
  size:
  - 350
  - 115
  type: PV
12:
  acqFunction: UCB
  acqHyperparameter: 2
  components:
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      units: ''
      value: 0
      valueType: float
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linksIn:
    10: decision
    20: decision
    21: decision
    22: decision
    23: decision
    26: decision
    27: decision
    28: decision
    29: decision
    30: decision
    31: decision
    32: decision
    33: kernel
    34: objective
  linksOut: {}
  mode: maximise
  name: Single Task GP
  numParticles: 10000
  numSamples: 5
  numSteps: 20
  position:
  - 5262.8596242004205
  - 6091.240278880384
  simPrecision: fp32
  size:
  - 600
  - 565
  type: Single Task GP
13:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 58
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 58)'
  position:
  - 4008
  - 6301
  size:
  - 350
  - 115
  type: PV
14:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 295
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 295)'
  position:
  - 4397
  - 6422
  size:
  - 350
  - 115
  type: PV
15:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 247
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 247)'
  position:
  - 4399
  - 6303
  size:
  - 350
  - 115
  type: PV
16:
  automatic: false
  components:
    dimensions:
      name: Dimensions
      type: KernelComponent
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  fontsize: 12
  hyperparameters:
    lengthscale:
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 1.0
    scale:
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linkedPVs:
    27:
    - 0
    - 100
    28:
    - 0
    - 100
    29:
    - 0
    - 100
    30:
    - 0
    - 100
    31:
    - 0
    - 100
    32:
    - 0
    - 100
  linksIn: {}
  linksOut:
    33: in
  name: RBF Kernel (LTB HSTRs)
  position:
  - 4257
  - 6851
  size:
  - 300
  - 374
  type: RBF Kernel
17:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 191
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 191)'
  position:
  - 4004
  - 6669
  size:
  - 350
  - 115
  type: PV
18:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 155
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 155)'
  position:
  - 4004
  - 6547
  size:
  - 350
  - 115
  type: PV
19:
  automatic: false
  components:
    dimensions:
      name: Dimensions
      type: KernelComponent
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  fontsize: 12
  hyperparameters:
    lengthscale:
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 1.0
    scale:
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linkedPVs:
    10:
    - 0
    - 100
    20:
    - 0
    - 100
    21:
    - 0
    - 100
    22:
    - 0
    - 100
    23:
    - 0
    - 100
    26:
    - 0
    - 100
  linksIn: {}
  linksOut:
    33: in
  name: RBF Kernel (LTB VSTRs)
  position:
  - 4582
  - 7098
  size:
  - 300
  - 374
  type: RBF Kernel
20:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 71
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 71)'
  position:
  - 4576
  - 5624
  size:
  - 350
  - 115
  type: PV
21:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 235
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 235)'
  position:
  - 4571
  - 5989
  size:
  - 350
  - 115
  type: PV
22:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 168
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 168)'
  position:
  - 4570
  - 5867
  size:
  - 350
  - 115
  type: PV
23:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 283
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 283)'
  position:
  - 4569
  - 6110
  size:
  - 350
  - 115
  type: PV
24:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 106
  linksIn: {}
  linksOut:
    34: in
  name: 'BPM (Index: 106)'
  position:
  - 4006
  - 6425
  size:
  - 350
  - 115
  type: PV
26:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 119
  linksIn: {}
  linksOut:
    12: decision
  name: 'VSTR (Index: 119)'
  position:
  - 4574
  - 5746
  size:
  - 350
  - 115
  type: PV
27:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 23
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 23)'
  position:
  - 4130
  - 5498
  size:
  - 350
  - 115
  type: PV
28:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 167
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 167)'
  position:
  - 4126
  - 5864
  size:
  - 350
  - 115
  type: PV
29:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 118
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 118)'
  position:
  - 4128
  - 5742
  size:
  - 350
  - 115
  type: PV
30:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 70
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 70)'
  position:
  - 4128
  - 5620
  size:
  - 350
  - 115
  type: PV
31:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 282
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 282)'
  position:
  - 4126
  - 6104
  size:
  - 350
  - 115
  type: PV
32:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 100
      min: 0
      name: Kick
      type: SliderComponent
      units: mrad
      value: 0.0
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linkedElement: 234
  linksIn: {}
  linksOut:
    12: decision
  name: 'HSTR (Index: 234)'
  position:
  - 4124
  - 5984
  size:
  - 350
  - 115
  type: PV
33:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  hyperparameters:
    lengthscale (RBF Kernel (LTB HSTRs)):
      description: lengthscale affects how rapidly correlation decays with distance
      type: vec
      value:
      - 1.0
    scale (RBF Kernel (LTB HSTRs)):
      description: magnitude of the kernel around the point
      type: float
      value: 1
  linksIn:
    16: in
    19: in
  linksOut:
    12: kernel
  name: Add
  position:
  - 4897
  - 6823
  size:
  - 350
  - 295
  type: Add
34:
  components: {}
  dtype: CHARGE
  dtypes:
  - CHARGE
  - X
  - Y
  - PX
  - PY
  linksIn:
    13: in
    14: in
    15: in
    17: in
    18: in
    24: in
  linksOut:
    12: objective
  name: Add
  position:
  - 4856
  - 6510
  size:
  - 250
  - 100
  type: Add
