0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 2359.0088330787557
  - 1804.5874022630114
  type: Editor
  zoom: 0.91987786123205
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 0
  linksIn: {}
  linksOut: {}
  name: PV
  position:
  - 1708
  - 1499
  size:
  - 325
  - 115
  type: PV
