0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 1973.0
  - 1707.0
  type: Editor
  zoom: 1
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Value
      type: SliderComponent
      units: ''
      value: 27.450999999999997
      valueType: float
  linksIn: {}
  linksOut: {}
  name: BS-PC-VSTR-01
  position:
  - 1641.0
  - 1544.0
  size:
  - 325
  - 115
  type: PV
