0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 969.2536110597832
  - 1093.9529060499308
  type: Editor
  zoom: 0.7056976545613418
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: SliderComponent
      units: mrad
      value: 0
  linksIn: {}
  linksOut: {}
  name: asvsajsabdasjhasd
  position:
  - 482
  - 857
  size:
  - 325
  - 115
  type: PV
7:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: SliderComponent
      units: mrad
      value: 0
  linksIn: {}
  linksOut: {}
  name: PV
  position:
  - 503
  - 1033
  size:
  - 325
  - 115
  type: PV
8:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: SliderComponent
      units: mrad
      value: 0
  linksIn: {}
  linksOut: {}
  name: PV
  position:
  - 651
  - 1197
  size:
  - 325
  - 115
  type: PV
