0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 1399.0
  - 1399.0
  type: Editor
  zoom: 1
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
